// This file is auto-generated by scripts/generate-registry.js
// Do not edit this file manually.

import config_0 from "@/data/applications/greenlight-swe-de.json";
import config_1 from "@/data/applications/test-company-b.json";
import config_2 from "@/data/applications/test-company.json";

export const applicationsRegistry: Record<string, unknown> = {
  "greenlight-swe-de": config_0,
  "test-company-b": config_1,
  "test-company": config_2,
};
